// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */
enum MonsterCatchResult {
  Missed,
  Caught,
  Fled
}

enum MonsterType {
  None,
  Leaffy,
  Firer,
  Grekky
}

enum TerrainType {
  None,
  Grass,
  Tree,
  Boulder,
  HasItem
}
